name 'jobs_app'
maintainer 'mwilkinson'
maintainer_email 'mwilkinson@trimastone.com'
license 'all_rights'
description 'Installs/Configures jobs_app'
long_description 'Installs/Configures jobs_app'
version '0.1.0'
depends 'poise-python'
depends 'runit'